apiVersion: v1
kind: Service
metadata:
  name: identityservice
spec:
  selector:
    app: identityservice
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservice
spec:
  selector:
    matchLabels:
      app: identityservice
  replicas: 1
  template:
    metadata:
      labels:
        app: identityservice
    spec:
      containers:
        - name: server
          image: ironicmageinc/identityservice
          ports:
            - name: http
              containerPort: 8080

---